IF  EXISTS (SELECT name FROM sys.databases WHERE name = N'MyDB')
		DROP	DATABASE [MyDB]
GO
CREATE DATABASE [MYDB] ON  PRIMARY 
( NAME = N'MYDB', FILENAME = N'C:\MSSQL2012\Data\MYDB_Data.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10% )
 LOG ON 
( NAME = N'MYDB_log', FILENAME = N'C:\MSSQL2012\Logs\MYDB_Log.ldf' , SIZE = 1024KB , MAXSIZE = UNLIMITED , FILEGROWTH = 10%)
GO
ALTER DATABASE [MYDB]
SET RECOVERY SIMPLE WITH NO_WAIT
GO

CREATE DATABASE [MYDB] ON  PRIMARY 
( NAME = N'MYDB', FILENAME = N'E:\Data\MYDB_Data.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10% )
 LOG ON 
( NAME = N'MYDB_log', FILENAME = N'F:\Logs\MYDB_Log.ldf' , SIZE = 1024KB , MAXSIZE = UNLIMITED , FILEGROWTH = 10%)
GO
ALTER DATABASE [MYDB]
SET RECOVERY SIMPLE WITH NO_WAIT
GO
USE		[master]
GO
CREATE DATABASE [DatabaseName] ON  PRIMARY 
( NAME = N'DatabaseName_dat', FILENAME = N'D:\MSSQL\Data\DatabaseName_dat.mdf' , SIZE = 10240KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10240KB ),
 FILEGROUP [INDEX] 
( NAME = N'DatabaseName_idx', FILENAME = N'D:\MSSQL\Indx\DatabaseName_idx.ndf' , SIZE = 10240KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10240KB )
 LOG ON 
( NAME = N'DatabaseName_log', FILENAME = N'D:\MSSQL\Logs\DatabaseName_log.ldf' , SIZE = 10240KB , MAXSIZE = 2048GB , FILEGROWTH = 10240KB )
GO

CREATE DATABASE [DatabaseName] ON  PRIMARY 
( NAME = N'DatabaseName_dat', FILENAME = N'D:\MSSQL\Data\DatabaseName_dat.mdf' , SIZE = 10240KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10240KB ),
 FILEGROUP [INDEX] 
( NAME = N'DatabaseName_idx', FILENAME = N'D:\MSSQL\Indx\DatabaseName_idx.ndf' , SIZE = 10240KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10240KB )
 LOG ON 
( NAME = N'DatabaseName_log', FILENAME = N'D:\MSSQL\Logs\DatabaseName_log.ldf' , SIZE = 10240KB , MAXSIZE = 2048GB , FILEGROWTH = 10240KB )
GO
